config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'items/index'
  get 'decks/choose'
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :decks, only: [:index, :new, :create, :show, :destroy] do
    member do
      get :progress
      get :close_vote
      put :hide
    end
  end
  resources :deck_items, only: [] do
    resources :votes, only: [:create]
  end
  get "items", to: "items#index"
end

app/views/shared/_card-resto.html.erb
<div class="card-item">
  <img src= <%=deck_item.item.photo_url %>>
  <div class="align-items-center card-item-infos d-flex">
    <div>
      <h2> <%= deck_item.item.name %> </h2>
      <p><%=deck_item.item.address%></p>
    </div>
    <div>
      <div class="ratings">
        <% deck_item.item.rating.round.times do  %>
          <i class="fa fa-star rating-color"></i>
          <% end %>
          <% (5 - deck_item.item.rating.round).times do  %>
            <i class='fa fa-star'></i>
          <% end %>
      </div>

      <div class="card-item-pricing">
       <% deck_item.item.price_range.times do%>
       €
      <% end %>

      </div>
    </div>

  </div>
</div>



<%# <div class="ratings"> %>
  <%# <% item.rating.times do  %>
     <%# <i class='fa fa-star rating-color'></i> %>
  <%# <% end %>
  <%# <% (5 - item.rating.times).times do  %>
      <%# <i class='fa fa-star'></i> %>
  <%# <% end %>
<%# </div> %>

app/views/shared/_card-swipe-movie.html.erb
<div class="swiper" data-controller="swipe coordinates">
  <div class="swiper__content">
    <div class="swiper__card-cont">
      <% @deck_items.each do |deck_item| %>
        <div class="swiper__card" data-swipe-target="card" data-id="<%= deck_item.id %>">
          <div class="swiper__card__content">
            <div class="swiper__card__content_top">
             <%# La partie du haut de la carte %>
            </div>
            <img src= <%=deck_item.item.photo_url %> class="swiper__card__img" />
            <div class="swiper__card__content_bottom">
              <p class="swiper__card__name">
              <strong><%= deck_item.item.name %></strong>
              </p>
              <p class="swiper__card__distance">
                <div class="ratings">
                <% deck_item.item.rating.round.times do  %>
                  <i class="fa fa-star rating-color"></i>
                  <% end %>
                  <% (5 - deck_item.item.rating.round).times do  %>
                    <i class='fa fa-star'></i>
                  <% end %>
                </div>
              </p>


            </div>
          </div>
          <div class="swiper__card__choice m--reject">
          </div>
          <div class="swiper__card__choice m--like">
          </div>
          <div class="swiper__card__drag">
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_card-swipe-restaurant.html.erb
<div class="swiper" data-controller="swipe coordinates">
  <div class="swiper__content">
    <div class="swiper__card-cont">
      <% @deck_items.each do |deck_item| %>
        <div class="swiper__card" data-swipe-target="card" data-id="<%= deck_item.id %>">
          <div class="swiper__card__content">
            <div class="swiper__card__content_top">
             <%# La partie du haut de la carte %>
            </div>
            <img src= <%=deck_item.item.photo_url %> class="swiper__card__img" />
            <div class="swiper__card__content_bottom">
              <p class="swiper__card__name">
              <strong><%= deck_item.item.name %></strong>
              </p>
               <div class="card-item-pricing">
                <% (deck_item.item.price_range + 1).times do%>
                €
                <% end %>
                </div>
              <p class="swiper__card__distance">
                <i class="fa-solid fa-location-dot pe-1"> </i><%= deck_item.item.address %>
                <div class="ratings">
                <% deck_item.item.rating.round.times do  %>
                  <i class="fa fa-star rating-color"></i>
                  <% end %>
                  <% (5 - deck_item.item.rating.round).times do  %>
                    <i class='fa fa-star'></i>
                  <% end %>
                </div>
              </p>

            </div>
          </div>
          <div class="swiper__card__choice m--reject">
          </div>
          <div class="swiper__card__choice m--like">
          </div>
          <div class="swiper__card__drag">
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_card-swipe.html.erb
<div class="swiper" data-controller="swipe coordinates">
  <div class="swiper__content">
    <div class="swiper__card-cont">
      <% @deck_items.each do |deck_item| %>
        <div class="swiper__card" data-swipe-target="card" data-id="<%= deck_item.id %>">
          <div class="swiper__card__content">
            <div class="swiper__card__content_top">
             <%# La partie du haut de la carte %>
            </div>
            <img src= <%=deck_item.item.photo_url %> class="swiper__card__img" />
            <div class="swiper__card__content_bottom">
              <p class="swiper__card__name">
              <strong><%= deck_item.item.name %></strong>, <span class="profile-age">€</span>
              </p>
              <p class="swiper__card__distance">
                <i class="fa-solid fa-location-dot pe-1"> </i><%= deck_item.item.address %>
                <div class="ratings">
                <% deck_item.item.rating.round.times do  %>
                  <i class="fa fa-star rating-color"></i>
                  <% end %>
                  <% (5 - deck_item.item.rating.round).times do  %>
                    <i class='fa fa-star'></i>
                  <% end %>
                </div>
              </p>


            </div>
          </div>
          <div class="swiper__card__choice m--reject">
          </div>
          <div class="swiper__card__choice m--like">
          </div>
          <div class="swiper__card__drag">
          </div>
        </div>
      <% end %>
  </div>
</div>

app/views/shared/_deck_winning_item.html.erb
<div class="page-wrapper">
  <h2> <strong> And the winner is ... </strong> </h2>

  <div class="winner-card" style="background-image: url('<%= winner.item.photo_url %>')">
    <div class="winner-card-info">
      <p><%= winner.item.name %></p>
      <p><%= winner.item.address %></p>
    </div>
  </div>
  <br>
  <div class="emoji-container">
    <% 10.times do  %>
        <div class="emoji" style="top: <%= rand(0..100) %>vh; left: <%= rand(0..100) %>vw;"> <h1>🎉</h1></div>
    <%end %>
  </div>

  <div data-controller="clip-board" data-clip-board-feedback-text-value="Copied!">
    <input style="opacity: 1; height: auto; width:auto; position: absolute; z-index: -1;" class="d-some" data-clip-board-target="input" type="text" value=" <%= deck_url(@deck) %>" readonly>
    <div class="bg"></div>
    <button class="btn btn-primary" data-action="click->clip-board#copy">Copier le lien</button>
  </div>
</div>

app/views/shared/_deck_winning_movie.html.erb
<div class="page-wrapper p-2">
  <h2> <strong> And the winner is ...</strong> </h2>

  <div class="winner-card" style="background-image: url('<%= winner.item.photo_url %>')">
    <div class="winner-card-info">
    </div>
  </div>
  <div class="emoji-container">
    <% 10.times do  %>
        <div class="emoji" style="top: <%= rand(0..100) %>vh; left: <%= rand(0..100) %>vw;"> <h1>🎉</h1></div>
    <%end %>
  </div>

  <div class="mt-3">
    <button class="close-btn" data-controller="sharing"
      data-action="click->sharing#share"
      data-sharing-title-value="<%= @deck.name %>"
      data-sharing-url-value="<%= deck_url(@deck) %>"><i class="fa-regular fa-share-from-square"></i> Share</button>

  </div>
</div>

app/views/shared/_deck_winning_restaurant.html.erb
<div class="page-wrapper p-2">
  <h2> <strong> And the winner is ... </strong> </h2>

  <div class="winner-card" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url('<%= winner.item.photo_url %>')">
    <div class="winner-card-info">
      <p><%= winner.item.name %></p>
      <p><%= winner.item.address %></p>
      <div class="ratings">
        <% winner.item.rating.round.times do  %>
          <i class="fa fa-star rating-color"></i>
          <% end %>
          <% (5 - winner.item.rating.round).times do  %>
            <i class='fa fa-star'></i>
          <% end %>
      </div>
    </div>
  </div>
  <div class="winning_phone">
    <div><p><i class="fa-solid fa-phone"></i> Call to book for <%= winner.deck.voters.count %> people <br><%= winner.deck.date&.strftime(" on %d %B %Y" ' @ ' "%l" ':' "%M%P") %></p></div>
    <div class="phone_number"> <%= winner.item.item_phone %></div>
  </div>
  <div class="emoji-container">
    <% 10.times do  %>
        <div class="emoji" style="top: <%= rand(0..90) %>vh; left: <%= rand(0..95) %>vw;"> <h1>🎉</h1></div>
    <%end %>
  </div>

  <div class="mt-3">
    <button class="close-btn" data-controller="sharing"
      data-action="click->sharing#share"
      data-sharing-title-value="<%= @deck.name %>"
      data-sharing-url-value="<%= deck_url(@deck) %>"><i class="fa-regular fa-share-from-square"></i> Share</button>

  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= notice %>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
    <%= alert %>
  </div>
<% end %>

app/views/shared/_ios_pwa_links.html.erb
<link rel="apple-touch-icon" sizes="57x57" href="<%= image_path 'icons/apple-icon-57x57.png' %>">
<link rel="apple-touch-icon" sizes="60x60" href="<%= image_path 'icons/apple-icon-60x60.png' %>">
<link rel="apple-touch-icon" sizes="72x72" href="<%= image_path 'icons/apple-icon-72x72.png' %>">
<link rel="apple-touch-icon" sizes="76x76" href="<%= image_path 'icons/apple-icon-76x76.png' %>">
<link rel="apple-touch-icon" sizes="114x114" href="<%= image_path 'icons/apple-icon-114x114.png' %>">
<link rel="apple-touch-icon" sizes="120x120" href="<%= image_path 'icons/apple-icon-120x120.png' %>">
<link rel="apple-touch-icon" sizes="144x144" href="<%= image_path 'icons/apple-icon-144x144.png' %>">
<link rel="apple-touch-icon" sizes="152x152" href="<%= image_path 'icons/apple-icon-152x152.png' %>">
<link rel="apple-touch-icon" sizes="180x180" href="<%= image_path 'icons/apple-icon-180x180.png' %>">
<link rel="icon" type="image/png" sizes="32x32" href="<%= image_path 'icons/favicon-32x32.png' %>">
<link rel="icon" type="image/png" sizes="96x96" href="<%= image_path 'icons/favicon-96x96.png' %>">
<link rel="icon" type="image/png" sizes="16x16" href="<%= image_path 'icons/favicon-16x16.png' %>">

app/views/shared/_message-deck-fin.html.erb
<% if @deck.user == current_user %>
  <div class="container d-flex flex-column align-items-center hidden-text pe-3">
  <h2 class="text-center fw-bold"> CONGRATS ! 🥳</h2>
  <p class="text-center fw-bold"> Share the list link to friends :
  <br>
  <div class="mt-3">
    <button class="create-btn" data-controller="sharing"
      data-action="click->sharing#share"
      data-sharing-title-value="<%= @deck.name %>"
      data-sharing-url-value="<%= deck_url(@deck) %>"><i class="fa-regular fa-share-from-square"></i> Share</button>

  </div>
   </p>

  <p class="text-center fw-bold"> You can close it from the dashboard!</p>
  </div>
<% else %>
  <div class="container d-flex flex-column align-items-center hidden-text pe-3">
  <h2 class="text-center fw-bold"> CONGRATS ! 🥳</h2>
  <p class="text-center fw-bold"> You've finished voting for propositions you liked, now share the deck's link to friends so they can vote as well :
  <br>
  <div class="mt-3">
    <button class="create-btn" data-controller="sharing"
      data-action="click->sharing#share"
      data-sharing-title-value="<%= @deck.name %>"
      data-sharing-url-value="<%= deck_url(@deck) %>"><i class="fa-regular fa-share-from-square"></i> Share</button>

  </div>
   </p>

<% end %>

app/views/shared/_navbar-mobile.html.erb
<div class="navbar-app d-flex justify-content-between p-3">
  <%= link_to decks_path, class:"d-flex flex-column align-items-center" do %>
   <%= image_tag("dashboards.png",
      style:"display: inline-block;
      height: 30px; width: 30px;
       object-fit: cover;")%>
    <div>
      Dashboard
    </div>
  <% end %>

  <%= link_to decks_choose_path, class:'link-center' do %>
    <i class="fa-solid fa-circle-plus navbar-btn"></i>
  <% end %>

  <div type="button" data-bs-toggle="collapse" data-bs-target="#navbarBottom" aria-controls="navbarBottom" aria-expanded="false" aria-label="Toggle navigation">
    <span class="d-flex flex-column align-items-center">
    <% if current_user.photo.attached? %>
      <%= cl_image_tag(current_user.photo.key,
      style:"display: inline-block;
      height: 30px; width: 30px;
       border-radius: 50%;
       object-fit: cover;")%>
    <%else   %>
        <%= image_tag("user.png",
      style:"display: inline-block;
      height: 30px; width: 30px;
       object-fit: cover;")%>
     <%end%>
      <div>
        Profile
      </div>
    </span>
  </div>

  <div class="collapse navbar-collapse navbar-collapse-custom" id="navbarBottom">
    <ul class="navbar-nav me-auto">
      <% if user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Edit profile", edit_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
            <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "Login", new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>
    </ul>
  </div>


</div>

app/views/shared/_navbar.html.erb
<% if user_signed_in? %>
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
<% else %>
<div class="navbar navbar-expand-sm navbar-dark navbar-lewagon">
<% end %>
  <div class="container-fluid">
  <div class="d-flex text-align-center">
    <%= link_to decks_path, class: "navbar-brand" do %>
      <%= image_tag "logo-noir.gif" %>
    <% end %>

  </div>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Dashboard", decks_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Nouvelle liste", decks_choose_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
              <%= link_to "Logout", destroy_user_session_path, data: {turbo_method: :delete}, class: "nav-link" %>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>

app/views/shared/_photo-voters.html.erb
<% deck.voters.each do |voter| %>
  <% if voter.photo.attached?%>
    <%= cl_image_tag(voter.photo.key,
    data: { controller: "tooltip"},
        title:  if voter.username.present?
                  voter.username
                else
                  voter.email.split("@").first
                end,
        style:"display: inline-block;
        height: 20px; width: 20px;
        border-radius: 50%;
        object-fit: cover;")%>
  <% else %>
    <%= image_tag("https://i.pinimg.com/280x280_RS/35/a1/e6/35a1e6d69cf6924b6076d864a5d39e95.jpg",
        data: { controller: "tooltip"},
        title:  if voter.username.present?
                  voter.username
                else
                  voter.email.split("@").first
                end,
        style:"display: inline-block;
        height: 20px; width: 20px;
        border-radius: 50%;
        object-fit: cover;")%>
  <% end %>
<% end %>

app/views/shared/_progress-bar.html.erb
 <div class="progress" data-controller="progress-bar" data-progress-bar-deck-id-value="<%= @deck.id%>">
    <div class="progress-bar" role="progressbar"
    style="background-color: #CCFF00; color: black; width: <%= completed_percent %>%;"
    aria-valuenow="<%= completed_percent %>"
    aria-valuemin="0" aria-valuemax="100"
    >
      <%= completed_percent %>%
    </div>
  </div>