config/routes.rb
Rails.application.routes.draw do
  post '/rate' => 'rater#create', :as => 'rate'
  get 'items/index'
  get 'decks/choose'
  devise_for :users, :controllers => {
    sessions: 'users/sessions',
    registrations: 'users/registrations'
  }
  root to: "pages#home"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  # Defines the root path route ("/")
  # root "articles#index"
  resources :decks, only: [:index, :new, :create, :show, :destroy] do
    member do
      get :progress
      get :close_vote
      put :hide
    end
  end
  resources :deck_items, only: [] do
    resources :votes, only: [:create]
  end
  get "items", to: "items#index"
end

app/models/deck.rb
class Deck < ApplicationRecord
  belongs_to :user
  validates :name, presence: true

  has_many :deck_items, dependent: :destroy
  has_many :items, through: :deck_items
  has_many :votes, through: :deck_items
  has_many :voters, -> { distinct }, through: :votes, source: :user

  def set_default_status
    self.status = 'pending'
  end

  def most_voted_deck_item
    self.deck_items.joins(:votes)
    .group('deck_items.id')
    .select('deck_items.*, SUM(votes.value) AS votes_count')
    .order('votes_count DESC, deck_items.created_at ASC')
    .first
  end
  #private

  #def set_default_status
  #  self.status = 'pending'
  #end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  def index
    @decks = Deck.all
    @all_my_decks = Deck.joins(:deck_items).joins(:votes).where("decks.user_id = ? OR votes.user_id = ?", current_user.id, current_user.id).distinct
    @my_decks = @all_my_decks.where.not(status: "Hidden").order(created_at: :desc)
    @pending_decks = @my_decks.where(status: "Pending").order(created_at: :desc)
    @closed_decks = @my_decks.where(status: "Closed").order(created_at: :desc)
    @hidden_decks = @my_decks.all.where(status: "Hidden").order(created_at: :desc)
  end

  def progress
    @user_id = current_user.id
    @deck = Deck.find(params[:id])
    @completed_percent =
      (@deck.deck_items.select{ |deck_item| deck_item.votes.where(user: current_user).any? }.size / @deck.deck_items.size.to_f * 100).round
    render json: { completed_percent: @completed_percent }
  end

  def choose
  end

  def new
    @deck = Deck.new
    @deckitem = DeckItem.new
  end

  def create
    @deck = Deck.new(deck_params)
    @deck.user = current_user
    @deck.item_type = params[:item_type]
    @deck.status = "Pending"
    if @deck.save!

      if params[:item_type] == "Restaurant"
        @items = Item.near(@deck.address, 10).limit(10)
        @items = @items.where("price_range >= ?", @deck.price_range)
      elsif params[:item_type] == "Movie"
        if params[:deck][:movie_genre] == "All"
          @items = Item.where(item_type: "Movie")
        else
          @items = Item.where(movie_genre: params[:deck][:movie_genre])
        end
      end
      @items.each do |item|
        deck_item = DeckItem.new(deck: @deck, item: item)
        deck_item.save!
      end
      redirect_to deck_path(@deck)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def show
    @deck = Deck.find(params[:id])
    @my_votes = Vote.where(user: current_user)
    @deck_items_voted = @my_votes.pluck(:deck_item_id)
    @deck_items = @deck.deck_items.where.not(id: @deck_items_voted)
    @deck_winning_item = @deck.most_voted_deck_item
    @win if @deck.status == "closed"
  end

  def close_vote
    @deck = Deck.find(params[:id])
    if @deck.update(status: "Closed")
      redirect_to deck_path(@deck), notice: "Vote closed successfully."
    else
      redirect_to deck_path(@deck), alert: "Error closing vote."
    end
  end

  def hide
    @deck = Deck.find(params[:id])
    @deck.status = "Hidden"
    @deck.save
    redirect_to decks_path
  end


  def destroy
    @deck = Deck.find(params[:id])
    @deck.destroy
    redirect_to decks_path
  end

  private

  def deck_params
    params.require(:deck).permit(:name, :date, :address, :rating, :price_range, :movie_title, :movie_genre, :item_type)
  end
end

app/views/decks/_deckcards.erb
<% decks.each do |deck| %>
  <div class="cards-deck">
    <div class="card-deck-body">
      <div class="row">
      <h5 class="card-deck-title mb-0"> <% if deck.user.photo.attached?%>
            <%= cl_image_tag(deck.user.photo.key,
                style:"display: inline-block;
                height: 30px; width: 30px;
                border-radius: 50%;
                object-fit: cover;")%>
          <% else %>
            <%= image_tag("https://i.pinimg.com/280x280_RS/35/a1/e6/35a1e6d69cf6924b6076d864a5d39e95.jpg",
                style:"display: inline-block;
                height: 20px; width: 20px;
                border-radius: 50%;
                object-fit: cover;")%>
          <% end %>
          <%= link_to deck.name, deck_path(deck), style:"text-decoration: none"%></h5>
        <p class="small text-secondary ">
          Proposed by
          <% if deck.user.username.present?%>
            <%= deck.user.username %>
          <% else %>
            <%= deck.user.email.split("@").first %>
          <% end  %>
      </p>
      <p> 📅 On <%= deck.date&.strftime("%d %B %Y" ' @ ' "%l" ':' "%M%P") %></p>
        <div class="container">
          <p> 🤼 Voters : <%= render "shared/photo-voters", deck: deck %>  </p>
          <% if deck.status == "Closed" %>
          <span class= "most-voted-item"> 🏆 <strong><%= deck.most_voted_deck_item.item.name %> </strong>🏆 </span>
          <% end %>
          <div class="d-flex justify-content-between mt-2">
            <button class="create-btn" data-controller="sharing"
              data-action="click->sharing#share"
              data-sharing-title-value="<%= deck.name %>"
              data-sharing-url-value="<%= deck_url(deck) %>"><i class="fa-regular fa-share-from-square"></i> Share</button>
          <% if deck.status != "Hidden" %>
            <%= link_to "", hide_deck_path(deck), style: "text-decoration: none", data: {turbo_method: :put, turbo_confirm: 'Are you sure?'}, class: "hide-icon fas fa-times" %>
          <% end %>
          <% if deck.user_id == current_user.id && deck.status == "Pending" %>
            <%= link_to "Close votes", close_vote_deck_path(deck), method: :put, class: "close-btn" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  </div>
<% end %>

app/views/decks/_decktabs.erb
<div class="container" style="margin-bottom: 120px">
  <div class="row">

    <div class="tab deck-tab d-flex justify-content-around">
      <button class="tablinks tab_btn all" onclick="openTab(event, 'mine')" id="defaultOpen">All</button>
      <button class="tablinks tab_btn pending" onclick="openTab(event, 'pending')">Pending</button>
      <button class="tablinks tab_btn closed" onclick="openTab(event, 'done')">Closed</button>
    </div>

      <div id="mine" class="tabcontent">
        <%= render partial: 'decks/deckcards', locals: {decks: @my_decks } %>
      </div>

      <div id="pending" class="tabcontent">
        <%= render partial: 'decks/deckcards', locals: {decks: @pending_decks} %>
      </div>

      <div id="done" class="tabcontent">
        <%= render partial: 'decks/deckcards', locals: {decks: @closed_decks} %>
      </div>
  </div>
</div>

<script>
function openTab(evt, tabName) {
  // Declare all variables
  var i, tabcontent, tablinks;

  // Get all elements with class="tabcontent" and hide them
  tabcontent = document.getElementsByClassName("tabcontent");
  for (i = 0; i < tabcontent.length; i++) {
    tabcontent[i].style.display = "none";
  }

  // Get all elements with class="tablinks" and remove the class "active"
  tablinks = document.getElementsByClassName("tablinks");
  for (i = 0; i < tablinks.length; i++) {
    tablinks[i].className = tablinks[i].className.replace(" active", "");
  }

  // Show the current tab, and add an "active" class to the button that opened the tab
  document.getElementById(tabName).style.display = "block";
  evt.currentTarget.className += " active";
}
// Get the element with id="defaultOpen" and click on it
document.getElementById("defaultOpen").click();
</script>

app/views/decks/choose.html.erb
<div class="container">
  <h1 class= "text-center"> Need a hand to choose...</h1>
    <div class="cards-choose">
      <%= link_to new_deck_path(deck: "Restaurant") do %>
        <div class="card-choose" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1564758564527-b97d79cb27c1?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=765&q=80)">
        Restaurant
        </div>
      <% end %>
      <%= link_to new_deck_path(deck: "Movie") do %>
        <div class="card-choose" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1535016120720-40c646be5580?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)">
          Movie
        </div>
        <% end %>
      <%= link_to new_deck_path(deck: "Gift") do %>
        <div class="card-choose" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.unsplash.com/photo-1512909006721-3d6018887383?ixlib=rb-4.0.3&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80)">
        Gift
        </div>
        <% end %>
    </div>
</div>

app/views/decks/index.html.erb
<%= render partial: 'decks/decktabs' %>

app/views/decks/new.html.erb
<div class="container py-3">
  <div class="row justify">
    <div class="col-12 col-md-6 offset-lg-3">
      <div class="deck-form" data-controller="range-slider">
        <h3>Create a new deck</h3>
        <%= simple_form_for @deck, data: { controller: 'flatpickr' } do |f| %>
         <%= f.error_notification %>
          <%= hidden_field_tag :item_type, params[:deck] %>
          <% if params[:deck] == "Restaurant" %>
            <%= f.input :name, placeholder: "name of your deck", input_html: { class: "form-control", required: true } %>
            <%= f.input :date, as: :string, input_html: { data: { flatpickr_target: "eventTime" } } %>
            <%= f.input :address, input_html: {data: {address_autocomplete_target: "address"}, class:"d-none"},
                        wrapper_html: {data: {controller: "address-autocomplete", address_autocomplete_api_key_value: ENV["MAPBOX_API_KEY"]}, class: "mapboxgl-ctrl-geocoder"}%>
            <%= f.input :price_range, input_html: { type: 'range', min: 0, max: 4, step: 1, class: 'form-range border-0', id: 'customRange3', data: { action: "input->range-slider#change"} } %>
            <p class="fw-bold text-center" style="font-size: 25px;" data-range-slider-target="euro">€€€</p>

          <% elsif params[:deck] == "Movie" %>
              <%= f.input :name, placeholder: "name of your deck" %>
              <%= f.input :date, as: :string, input_html: { data: { flatpickr_target: "eventTime" } } %>
              <%= f.input :movie_genre,
                          as: :radio_buttons,
                          collection_wrapper_tag: 'div',
                          collection_wrapper_class: 'category-wrapper',
                          item_wrapper_class: 'category-item',
                          input_html: {class: 'category-selector'},
                          collection: [["All<br>🎥".html_safe, "All"], ["Comedy<br>😂".html_safe, "Comédie"], ["Drama<br>😭".html_safe, "Drame"]],
                          checked: "All" %>
            <% else %>
              <%= f.input :name, placeholder: "name of your deck" %>
              <%= f.input :date, as: :string, input_html: { data: { flatpickr_target: "eventTime" } } %>
              <%= f.input :price_range, collection: ([['€', '€'], ['€€', '€€'], ['€€€', '€€€'], ['€€€€', '€€€€']]).to_a %>
           <% end %>
          <%= f.submit "Validate", class: "create-btn w-100"  %>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/decks/show.html.erb
<% if @deck.status == "Closed" && @deck.item_type == "Restaurant" %>
<% @win = true%>
  <%= render "shared/deck_winning_restaurant", winner: @deck_winning_item, decks: @decks %>
<% elsif @deck.status == "Closed" && @deck.item_type == "Movie" %>
<% @win = true%>
  <%= render "shared/deck_winning_movie", winner: @deck_winning_item, decks: @decks %>
<% else  %>
  <%= render "shared/progress-bar", completed_percent: @completed_percent%>
  <% if @deck.item_type == "Restaurant"%>
    <%= render "shared/card-swipe-restaurant", deck_items: @deck_item %>
    <%=  render "shared/message-deck-fin", deck: @deck%>
  <% elsif @deck.item_type == "Movie"%>
    <%= render "shared/card-swipe-movie", deck_items: @deck_item %>
    <%=  render "shared/message-deck-fin", deck: @deck%>
  <% end %>
<% end %>